# sources=foo.c bar.c
# sinclude $(sources:.c=.d)
.PHONY:all
all:
	@echo $(SHELL)
	@echo $(MAKE)
	@echo $(CURDIR)
	@echo $(MAKEFLAGS)
	@echo $(MAKEFILES)
	@echo $(srcdir)
	@echo $(CC)
	@echo $(NSTALL_DATA)

